---
title: "PlotLOO"
output: html_document
date: "2025-01-27"
---

```{r setup, include=FALSE}
#Add to folder: "all_loo_predictions.xlsx", "all_loo_predictions_no_ctrl.xlsx", "LOO_Analysis_Results_20_iters_10k_fold"
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
Before running this code, ensure you have ran steps 1, 2, 3, and 4
The figure generated here is the LOO figure in the paper (Figure 2)

Run the code in PlotLOOFunc
```{r}
# Function call example

#"../Step4_GenerateLOOResults/all_loo_predictions_20_iters.xlsx"
#"../Step2_GeneratePythonControlData/XGBoost_Analysis_10k_20i_details_fig1_Control_Results.xlsx"
source("PlotLOOFuncs.R")

check <- read.xlsx("../Step2_GeneratePythonControlData/XGBoost_Analysis_10k_20i_details_fig1_Control_Results.xlsx")

df <- read.xlsx("../Step4_GenerateLOOResults/all_loo_predictions_20_iters_with_ID.xlsx") %>%
  filter(Grp_Sex != "M_Cont_12")


write.xlsx(df, "all_loo_predictions_no_ctrl.xlsx")

results <- process_and_visualize_loo_results(
  all_loo_predictions_file = "all_loo_predictions_no_ctrl.xlsx",
  control_predictions_file = "../Step2_GeneratePythonControlData/XGBoost_Analysis_10k_20i_details_fig1_Control_Results.xlsx",
  output_prefix = "../Paper_Figures/020325_LOO_Analysis_Results_20_iters_10k_fold"
)

# Display the graph
print(results$combined_graph)

# Print significant results
significant_results <- results$t_test_results %>%
  filter(p_value < 0.05) %>%
  arrange(Dataset, p_value)

print("Significant results (p < 0.05):")
print(significant_results)



```

Save text files with dependencies and version
```{r}

# Get the R version
r_version <- R.version.string

# Get the list of loaded packages and their versions
loaded_packages <- sessionInfo()$otherPkgs
package_info <- data.frame(
  Package = names(loaded_packages),
  Version = sapply(loaded_packages, function(pkg) pkg$Version),
  stringsAsFactors = FALSE
)

# Define the output file
output_file <- "../Paper_Figures/Package_Info/Step6_R_session_and_packgage_version_info.txt"

# Write the R version to the file
writeLines(paste("R Version:", r_version), output_file)

# Write the package information
write.table(package_info, file = output_file, append = TRUE, row.names = FALSE, sep = "\t", quote = FALSE)

cat("Session info written to", output_file, "\n")


```